### ISSUE TITLE
API Standardization, Linting, and Compliance

### ISSUE THREAD

**Issue by ChristineP2** [SmartBear/intellij-swaggerhub-release#17]
It would be ideal if the errors/warnings I receive in the JetBrains SwaggerHub Plugin were the same as the errors/warnings I see in the Cloud when I check my work there. (Custom Rules, standard rules, linting rules, etc. should all be the same in both environments).

For example, within my IDE, I am receiving an erroneous error: “Schema validation: Missing required property 'swagger' = 2.0” on an openAPI3 schema that has the mutually exclusive property openapi: “3.0.1”. That is not reported on cloud at all.

**Comment by ptrsd** [comment]
Hi @ChristineP2 ,

Thanks for your feedback. Solution for "Missing required property 'swagger' = 2.0” on an openAPI3 schema that has the mutually exclusive property openapi: “3.0.1”. " is a part of the 1.0.6 version of the plugin.
