### ISSUE TITLE
Compatibility with the version 2022.2

### ISSUE THREAD

**Issue by ghaverbe** [SmartBear/intellij-swaggerhub-release#19]
The SwaggerHub API plugin for IntelliJ is not compatible with the current version of the IDE (IntelliJ IDEA 2022.2)
![InteliJ-Plugin_ErrorMsg](https://user-images.githubusercontent.com/21997964/185853635-cc4eb785-9ecf-4c93-8e31-e7721da8fe0e.png)

**Comment by allanlaal** [comment]
@SmartBear please remove `<idea-version>` attribute `until-build` in the compiled `intellij-swaggerhub-x.y.z.jar` `/META-INF/plugin.xml` or set it to `999.*`.

if you started off with https://github.com/JetBrains/intellij-platform-plugin-template then just change this line in `gradle.properties`:

	pluginUntilBuild = 999.*



this way your excellent plugin will work in all future IntelliJ releases and you don't have to keep changing this number every time Jetbrains releases a new version :)

AND if something breaks, you'll get users submitting error reports of the broken feature, not that you didn't react in time to increment `until-build`  again.

**Comment by ptrsd** [comment]
@ghaverbe New version was released yesterday.

@allanlaal Thank you for pointing out the potential solution and nice words about the plugin! 

Thank you for reaching out!

**Comment by allanlaal** [comment]
actually a better solution is just removing pluginUntilBuild

(I found out JB Marketplace might be blocking plugins with 999.*)
