### ISSUE TITLE
Needs update for IntelliJ 2023

### ISSUE THREAD

**Issue by thekiddreturns** [SmartBear/intellij-swaggerhub-release#20]
This plugin does not work with the latest IntelliJ. It needs an update.

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3
GC: G1 Young Generation, G1 Old Generation

<img width="582" alt="Screenshot 2023-04-08 at 10 44 10 AM" src="https://user-images.githubusercontent.com/19298586/230735585-8016f0bf-288f-4a7e-bbfa-3cf7a965ae52.png">

**Comment by jgubo-mct** [comment]
We are in desperate need of an update too!

**Comment by CalemRoelofsSB** [comment]
Hi @thekiddreturns @jgubo-mct, version 1.0.10 of the plugin is now available on the JetBrains marketplace.
https://plugins.jetbrains.com/plugin/16926-swaggerhub-api-design-by-smartbear/versions/stable/323320
This release is fully compatible with the newest version of Intellij (2023.1).
Thank you for your patience and let us know if you encounter any issues!
