### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ArGeBre** [SmartBear/intellij-swaggerhub-release#21]
Is anyone from smartbear actively maintaining this plugin?

**Comment by ponelat** [comment]
Yessir, although we could use all the help we can get :)

**Comment by ArGeBre** [comment]
Good to hear ;-) The project seems to be closed source though, so no way to provide help... I could offer to test, however I cannot even use the plugin. I am behind a firewall, and the plugin refuses to respect the proxy settings. See #11

**Comment by Torgh** [comment]
Hi, I will close this ticket. Yes, project still alive and is maintain how much is possible.
