### ISSUE TITLE
Cannot Access My Organization's APIs

### ISSUE THREAD

**Issue by sehand** [SmartBear/intellij-swaggerhub-release#4]
I've followed the instructions here (https://github.com/SmartBear/intellij-swaggerhub-release) to configure the SwaggerHUB Intellij plugin and am not able to see my organization's APIs.

Connection info is: https://app.swaggerhub.com
API Key: obtained from my profile info in SwaggerHUB
Organization added: Smartsheet

I see the following errors in the Intellij Event Log. I am using Intellij version 2021.1.1 (Ultimate Edition)

```
11:17 AM	java.lang.IllegalStateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
					 at [Source: (byte[])"<!doctype html>
					Build, Collaborate & Integrate APIs | SwaggerHub
					<link rel="canonical" href="https://swagger"[truncated 8714 bytes]; line: 1, column: 2]
```

**Comment by emmett008** [comment]
Hi @sehand ,

Thanks for your feedback, if you update the connection info to https://api.swaggerhub.com you should be able to see your organization's APIs.

**Comment by sehand** [comment]
Silly me! What the difference one character can make. I didn't look carefully enough. Thanks!!! It's working now!
