### ISSUE TITLE
Plugin autocorrects syntax erroneously (removes commas)

### ISSUE THREAD

**Issue by sehand** [SmartBear/intellij-swaggerhub-release#6]
In some of my enumerations, I interleave comments that group various values together. I cannot do this in the Plugin - it automatically/repeatedly removes the commas that separate values.

For example, in this enum, it refuses to let me type the required comma after "DOMAIN_NEEDS_VALIDATION" and "NOT_FOUND". It's very likely that the other commas were only allowed because I entered them via SwaggerHUB web page.

```
              enum:
                [
                  # INVALID_AUTHORIZATION
                  "ACCESS_DENIED_ERROR",

                  # MALFORMED_REQUEST
                  "ARGUMENT_TYPE_MISMATCH",
                  "DATATYPE_CONVERSION_ERROR",
                  "MISSING_HEADER",

                  # BUSINESS_RULE_VIOLATION
                  "DOMAIN_ALREADY_IN_USE",
                  "DOMAIN_NEEDS_VALIDATION"

                  # NOT_FOUND
                  "NOT_FOUND"

                  # TIMEOUT_ERROR
                  "TIMEOUT",

                  # INTERNAL_ERROR
                  "DATA_ACCESS_ERROR",
                  "UNEXPECTED_ERROR"
                ]
```

**Comment by emmett008** [comment]
Hi @sehand,

We have identified the issue re validation and are working on a fix presently.  Once it place we will generate another release with the fix. This should close close both this issue and https://github.com/SmartBear/intellij-swaggerhub-release/issues/5

**Comment by emmett008** [comment]
This issue has been resolved in the latest version of the plugin
