### ISSUE TITLE
Corruption in SwaggerHUB Plugin (also errors in SwaggerHUB webpage)

### ISSUE THREAD

**Issue by sehand** [SmartBear/intellij-swaggerhub-release#8]
I am getting errors in the SwaggerHUB plugin when I try to sync all APIs/DOMAINs with SwaggerHUB. I'm also seeing errors using the SwaggerHUB webpage. 

****
I can now no longer see any of my DOMAINs in the Intellij plugin and as a result am pretty much blocked with using the plugin in a meaningful way.
****

The 404 error from the plugin is for an API spec I deleted through the plugin and then I created a new one with a different version. I'm not sure why it is still complaining about the one I deleted.

Here's what the Plugin errors are:
```
2:06 PM	SwaggerHub
				Organization Smartsheet
				Open settings

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 404 code. Response: [Unknown API Smartsheet/UserAdmin-GroupManagement:1.0.0]

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: e9efa8a82e4d598d)]

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: 3bf06658f13e67dc)]

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: 720c08dd51c1522c)]

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: e72e30c0243b625e)]

2:06 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 404 code. Response: [Unknown API Smartsheet/UserAdmin-GroupManagement:1.0.0]

2:06 PM	SwaggerHub
				Organization Smartsheet
				Open settings

2:07 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: b6dad8295f18254f)]

2:07 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 404 code. Response: [Unknown API Smartsheet/UserAdmin-GroupManagement:1.0.0]

2:07 PM	com.smartbear.swaggerhub.intellij.plugin.client.ClientException: Request failed with 500 code. Response: [There was an error processing your request. It has been logged (ID: 8605ee5943f634a4)]

2:07 PM	SwaggerHub
				Organization Smartsheet
				Open settings
```

Here is an example error I am seeing in SwaggerHUB webpage:
```
Error.There was an error processing your request. It has been logged (ID: ff5d71336fe9cdf5)
```

**Comment by sehand** [comment]
As best as I can tell - is it possible that the plugin sync has issues if there are errors in the API/DOMAIN definitions? Once I resolved all the issues from within SwaggerHUB webpage, the plugin sync still shows a few errors (the 404 from above and the following one) but I can at least see all my APIs and DOMAINs again.

```
2:40 PM	com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@30e8d59d
				Current thread: Thread[JobScheduler FJ pool 16/11,4,Idea Thread Group] 402534379
				SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 987558231
```

**Comment by emmett008** [comment]
Hi Sehand,

There was an issue on production that may have caused the 404/500 errors you experienced. 
However, we will test the scenario that you described when there are errors in the api/domain definitions to ensure we have this covered

**Comment by emmett008** [comment]
@sehand, have retested this scenario with the latest version (1.0.2) and is now working as expected. 
Even if api/domain has validation issue in webpage, the sync will pull the definitions into plugin display.

Validation in the api definition will indicate the issue in IDE, however this validation is not in place for domains yet
